# Generated by Django 5.2.1 on 2025-09-02 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='addess',
            new_name='address',
        ),
    ]
