# Generated by Django 5.2.1 on 2025-09-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_addess_student_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='SubjectId',
            new_name='subject_id',
        ),
    ]
