# Generated by Django 5.2.1 on 2025-09-03 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_subjectid_teacher_subject_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='addess',
            new_name='address',
        ),
    ]
